config/routes.rb
Playlistic::Application.routes.draw do

  root 'welcome#index'
  get '/player', to: 'playlist#create', as: :build_playlist

end

app/models/playlist.rb
class Playlist
  attr_accessor :songs, :artist

  def self.get_playlist_by_similar_artist(artist)
    # pp response.parsed_response["response"]["songs"].map { |song| song["title"] }

    # Song.new(response.parsed_response["response"]["songs"].last)

    array_of_songs = artist_search(artist)["response"]["songs"].map { |song| 
      if song["tracks"].length > 0 
        Song.new(song) 
      end
      }

      playlist = Playlist.new
      playlist.songs = array_of_songs.compact
      playlist.artist = artist
      playlist
    # could have also used array_of_songs.delete("nil") to remove nil elements
    # songs is an array
    # {:response => { :songs => [{:id => "1"}, {:id => 2}, {:id => 3}] } }
  end

  def self.artist_search(artist)
    HTTParty.get("http://developer.echonest.com/api/v4/playlist/static?api_key=#{ENV["ECHO_API_KEY"]}&artist=#{artist}&format=json&results=10&type=artist-radio&bucket=id:spotify-WW&bucket=tracks").parsed_response
  end



end

app/models/song.rb
class Song 
  attr_accessor :artist_name, :title, :foreign_id

  def initialize(hash)
    self.artist_name = hash["artist_name"]
    self.foreign_id = hash["tracks"].first["foreign_id"]
    # self.title = hash["title"]

    puts foreign_id
  end

  def spotify_id
    self.foreign_id.sub("spotify-WW:track:", "")
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlist_controller.rb
class PlaylistController < ApplicationController

  def create
    search_term = (params[:artist])
    uri = URI::encode(search_term)
    @playlist = Playlist.get_playlist_by_similar_artist(uri)


    @tracks = @playlist.songs.map do |track| 
      track.spotify_id.sub("spotify:track:", "")
    end
    @tracks = @tracks.join(",")

    render "welcome/index"
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playlistic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Over+the+Rainbow' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Cutive+Mono' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/playlist/_form.html.erb
<%= form_tag(build_playlist_path, method: "get") do %>
   <%= label_tag(:type, "Create a") %>
  <%= select_tag(:type, options_for_select([["Artist", "by_artist"], ["Genre", "by_genre"]])) %> playlist.<br>
  <%= label_tag(:search, "Search:") %>
  <%= text_field_tag(:search) %>
  <%= submit_tag("Go") %>
<% end %>

app/views/playlist/player.html.erb
<iframe src="https://embed.spotify.com/?uri=spotify:trackset:PREFEREDTITLE:<%= @tracks %>" frameborder="0" allowtransparency="true"></iframe>

<iframe src="https://embed.spotify.com/?uri=spotify:trackset:PREFEREDTITLE:5Z7ygHQo02SUrFmcgpwsKW,1x6ACsKV4UdWS2FMuPFUiT,4bi73jCM02fMpkI11Lqmfe" frameborder="0" allowtransparency="true"></iframe>

app/views/welcome/index.html.erb
<div id="content-container">
  <h1 id="logo">Playlistic</h1>
  <%= image_tag "playlistic.jpg", alt: "mixtape"%>


  <h2>Create a playlist based on your favorite artist:</h2><br>

  <%= render "playlist/form" %><br>

  <% if @tracks.present? %>
    <iframe src="https://embed.spotify.com/?uri=spotify:trackset:<%= @tracks %>" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
  <% end %>
</div>